var logoImgs = [
    ['./images/mushroam/mushroam_logo4x.png','Mushroam logo. It was done in a pixel style to match the characters. Dither patterns are used in various parts of Mushroam, most notably in the menus, so a dither was incorporated here as well to match that.'],
    ['./images/blobs/blobs_logo.png','The Blobs Fight logo. The goal was to give a very stylized feeling but also represent the blobbiness and cuteness of the characters.'],
    ['./images/logos/logos_busbuddy.png','Busbuddy Ottawa logo. The app seeks to make the experience of using OCTranspo more friendly by giving real-time information, so for the logo I created a friendly version of the front of an OCTranspo bus. Thw two windows became eyes, the display bar at the top was split to create eyebrows, the hood became a smile, and the rear-view mirrors became ears.'],
    ['./images/logos/logos_skypyre.png','SkyPyre Studios logo. See below for a more detailed process breakdown.'],
    ['./images/logos/logos_personal.png','Personal logo. I wanted to incorporate a number of things into my logo. Firstly, I wanted to use my initials (DD) and create a symbol from them. Secondly I wanted to evoke something of a flame to suggest a spark of creativity. For the visual design, I wanted to create a crisp clear shape but also be a bit playful. <>'],
    ['./images/abyrinth/abyrinth_logo.png',
    'The current ABYRINTH logo. The goal was to create a wordmark that was tastefully sci-fi without being too unreadable. A swooshing trail and an angular dot on the I were added to suggest a space ship or a planetary ring.']
]

var abyrinthImgs = [
    ['./images/abyrinth/abyrinth_boi.png',
    '<p>The current model for Mylo, Abyrinth&apos;s main character. His look is emblematic of the character art style I am targeting. For this style, I sought to leverage two aspects: </p><p>One - A focus on strong, simple shapes, </p><p>Two - Pixel art that evokes a lived-in look. </p><p>Furthermore, Mylo&apos;s design needs to feel childish and small. Therefore, his limbs are long and gangly and his torso is covered by some sort of oversized shirt.</p>'],
    ['./images/abyrinth/abyrinth_eezoh.png',
    'Concept art for Mylo&apos;s uncle, Eezoh. Eezoh&apos;s design needed to convey a solidity and confidence while still fitting within the diminutive exaggerated proportions of Mylo&apos;s species.'],
    ['./images/abyrinth/abyrinth_flame.gif',
    'A small flame effect. Along with simplified models, I am also seeking to have simple and clean effects.'],
    ['./images/abyrinth/abyrinth_gun.png',
    'A pistol model. An initial test of props in the general art style.'],
    ['./images/abyrinth/abyrinth_spark.gif',
    'A small effect when mechanical devices take damage. There are multiple components to it, including several simple effects and an animated lightning beam.'],
    ['./images/abyrinth/abyrinth_pouncer.png',
    '<p>The model for the Pouncer enemy. The initial design was a reference to an older enemy from a previous game, but retooled to be more imposing.</p> <p>The design emphasizes long limbs and slenderness because this is an enemy that leaps far and moves quickly.</p>'],
    ['./images/abyrinth/abyrinth_kimin.png',
    'Concept art for the character of Kimin, a mining foreman aboard Abyrinth station. The workers of Abyrinth have various jobs but there will be some similarities in their uniforms. Kimin&apos;s represents the ruggedness of his job while also conforming to his species&apos;s unique needs.'],
    ['./images/abyrinth/abyrinth_grunt.png',
    'The model for the Grunt enemy. The goal visually was for it to look tough but not particularly fast. In the game, the grunt is resistant to damage, but easy to evade. '],
    ['./images/abyrinth/abyrinth_therae.jpg',
    'Concept art for a non-specific member of the therae species. The purpose of this piece was to explore the general posture, structure, and head shape.'],
    ['./images/abyrinth/abyrinth_mine.png',
    'The model for the flying mine. The flying mine is a small airborne enemy. The goal visually was to convey that it was a mine, so I gave it spikes to evoke a sea mine. '],
    ['./images/abyrinth/abyrinth_miner.jpg',
    'An initial concept for a miner working aboard abyrinth. Their outfit matches Kimin&apos;s, but they have a helmet. The helmet serves to anonymize them so they can serve as a generic character.'],
    ['./images/abyrinth/abyrinth_halen.png',
    'The model for the character of Halen as she appears in Abyrinth. The model was also a testbed for modelling and rigging a more human style character.'],
    ['./images/abyrinth/abyrinth_gunner.png',
    'The model for the Gunner enemy. In game, the right arm has a large rotating minigun attached to it. The gunner functions as a larger and more dangerous version of the grunt.'],
    ['./images/abyrinth/abyrinth_ui1.png',
    'The current HUD. There is an animated dither that runs through, evoking a holographic device that is not working perfectly. The blocks on the bottom left represent Mylo&apos;s health. Throughout the game, you can increase your maximum health by collecting fruit. The count of total fruit and how long until gaining more health is on the right side. Above the health are different blocks, each indicating a different ability you have found.'],
    ['./images/abyrinth/abyrinth_ui2.png',
    'Example of a page in the menu. All settings work and save across play sessions. The menu style uses dithers to give it visual cohesion with the rest of the game.'],
    ['./images/abyrinth/abyrinth_screen1.png',
    'A test scene. It uses various textures and models made for the game to simulate how they all will work together in the final product.'],
    ['./images/abyrinth/abyrinth_screen2.png',
    'An experiment using simple textures and binary space partitioning to create an angular environment. It was part of explorations into how the levels might look.'],
    ['./images/abyrinth/abyrinth_holo.png',
    'Explorations into creating a hologram effect. The look is intended to mimic something like a CRT television, with individual dots of light in the air.'],
    logoImgs[5],
    ['./images/abyrinth/abyrinth_mainmenu.png',
    'The current main menu, using placeholder assets for the scene. It is intended to depict Abyrinth station amidst an asteroid field.']
]

var blobsImgs = [
    ['./images/blobs/blobs_screen1.png','One of the maps, a sewer stage. Hazards featured werefalling globs of slime, a running waterfall, and areas to fall off the map.'],
    ['./images/blobs/blobs_screen2.png','One of the maps, a factory stage. Hazards included conveyor belts and fire.'],
    ['./images/blobs/blobs_screen3.png','One of the maps, a lava stage. The hazard was lava. Also displayed is a ring for the king of the hill mode.'],
    ['./images/blobs/blobs_screen4.png','One of the maps, a prison stage. The hazard was a spotlight which activated a machine gun.'],
    logoImgs[1],
    ['./images/blobs/blobs_icon.png','An icon, also used for printed stickers.']
]

var evasiveImgs = [
    ['./images/evasive/evasive_hunterfx.png','A hunter ship, performing a boost.'],
    ['./images/evasive/evasive_customization.gif','A sample of the hunter customization screen. For each the hunters and runners there were four ships to choose from. From there the painted pattern and the two colours it was made of could be selected.'],
    ['./images/evasive/evasive_artemis.png','Shield walls.'],
    ['./images/evasive/evasive_kauthen.png','A desert sandstorm.'],
    ['./images/evasive/evasive_reyliant.png','The minature sun at the heart of an alien installation.'],
    ['./images/evasive/evasive_zehil.png','Uncanny reflective waters between dimensions.'],
    ['./images/evasive/evasive_hunter1.png','A hunter ship, the avenger.'],
    ['./images/evasive/evasive_hunter3.png','A huter ship, the scythe.'],
    ['./images/evasive/evasive_runner3.png','A runner ship, the raven.'] 
]

var spImgs = [
    ['./images/logos/logos_sp1.png',
    'Original by Michael Dillabough'],
    ['./images/logos/logos_sp2.png',
    'Ininital exploration involved figuring out what general form the new meteor would take and how it would be integrated with the text. The basic idea was hit upon fairly quickly but from then on involved refining. A first idea had the meteor dissolving into squares to keep the squares from the original in a new way.'],
    ['./images/logos/logos_sp3.png',
    'Colour explorations.'],
    ['./images/logos/logos_sp4.png',
    'Further colour exploration as well as experimenting with alterations to the meteor. The dissolving was moved inside the shape to keep the overall silhouette stronger. We were also seeing how it might work in black and white.'],
    ['./images/logos/logos_sp5.png',
    'Further colour exploration.'],
    ['./images/logos/logos_sp6.png',
    'Further colour exploration as well as adjusting the amount of dissolving present.'],
    ['./images/logos/logos_sp7.png',
    'Different visual representations of dissolving were explored as well as again testing how the meteor was incorporated with the text.'],
    ['./images/logos/logos_sp8.png',
    'A simplified dissolve pattern was tried. Different embellishments were tried to better incorporate the text with the meteor.'],
    ['./images/logos/logos_sp9.png',
    'Different colour variations with the text and embellishments, as well as more ideas about the meteor dissolve.'],
    ['./images/logos/logos_sp10.png',
    'Focus shifted to refining the silhouette of the meteor to balance a feeling of momentum without stretching it too far.'],
    ['./images/logos/logos_sp11.png',
    'A new silhouette having been settled upon, we explored different dissolves, looking to evoke more of a firey feeling. This new shape was tried with different colours.'],
    ['./images/logos/logos_sp12.png',
    'More colour explorations and a new dissolve type.'],
    ['./images/logos/logos_sp13.png',
    'Explorations of variations on the new dissolve and relative sizing of the elements.'],
    ['./images/logos/logos_sp14.png',
    'The dissolve was settled on and colour explorations continued, including exploring a single colour variation.'],
    ['./images/logos/logos_sp15.png',
    'A similar page, this time seeing how the design fared on black.'],
    ['./images/logos/logos_sp16.png',
    'The shape having been settled and the rough colours settled, the exact colours were sought.'],
    ['./images/logos/logos_sp17.png',
    'The final colours were settled. Once again it was experimented to see alternative ways to incorporate the meteor.'],
    ['./images/logos/logos_sp18.png',
    'Seeing if an upward meteor could work.'],
    ['./images/logos/logos_sp19.png',
    'Further experiments with incorporating the meteor.'],
    ['./images/logos/logos_skypyre.png','The final design']
]

var mushImgs = [
    ['./images/mushroam/mushroam_mushbig.png','Mush! The default character of the game.'],
    ['./images/mushroam/mushroam_topsbig.png','The stoic Tops.'],
    ['./images/mushroam/mushroam_veilbig.png','The elusive Veil.'],
    ['./images/mushroam/mushroam_celiabig.png','The determined Celia.'],
    ['./images/mushroam/mushroam_sporabig.png',
    'The stout Spora.'],
    ['./images/mushroam/mushroam_truffbig.png',
    'The eager Truff.'],
    ['./images/mushroam/mushroam_bolobig.png',
    'The friendly Bolo.'],
    ['./images/mushroam/mushroam_capibig.png',
    'The confident Capi.'],
    ['./images/mushroam/mushroam_characters.png',
    'The in-game sprites of the various playable characters.'],
    ['./images/mushroam/mushroam_otherpixel.png',
    'Sundry other pixel art, including menu fx, npcs, and hazards.'],
    ['./images/mushroam/mushroam_logo4x.png',
    'The Mushroam logo. It was done in a pixel style to match the characters.'],
    ['./images/mushroam/mushroam_forestvoxels.png',
    'modular pieces for the first chapter of the game, set above the ground in a forest.'],
    ['./images/mushroam/mushroam_ruinvoxels.png',
    'modular pieces for the second chapter of the game, set in a cavern filled with ruins.'],
    ['./images/mushroam/mushroam_cityvoxels.png',
    'Modular pieces for the second chapter of the game, in which the player explores a vast city.'],
    ['./images/mushroam/mushroam_lairvoxels.png',
    'Modular pieces for use in the fourth chapter of the game, in which the player explores a civilization dedicated to the ants.'],
    ['./images/mushroam/mushroam_forestworld.png',
    'A level featured in the demo.'],
    ['./images/mushroam/mushroam_ruinworld.png',
    'A level featured in the demo.'],
]

var otherImgs = [
    ['./images/other/other_Annatara2.png','ANNATARA OF THE CRYSTAL STYLE. A piece done for a fantasy character who combined the armour and weapons of a knight with psionic powers. Initial versions of thep piece explored more relaxed and grounded postures to hold a halberd with, but given the fantasy powers of the character, I opted for a pose that emphasized the magic, suggesting she might be flying. '],
    ['./images/other/other_Slashheart.jpg','LADY SLASHHEART. A test to incorporate a character in a scene with specific lighting.'],
    ['./images/other/other_3dXopex.png','GADINSPIDOS XOPEX. A low-poly fantasy character made as practice.'],
    ['./images/other/other_Awaken_The_Blade.png','AWAKEN THE BLADE. A redone version of some old concept art for Halen: Ballad of the Blade Thief\'s spotify album.'],
    ['./images/other/other_Dak_At_Peace.png','DAK AT PEACE. A piece done to evoke a mood and explore posing when a chareacter is hanging on somwthing, rather than standing on ground.'],
    ['./images/other/other_Eideron.jpg','EIDERON. A concept for a fantasy character who combined aspects of a warrior and a wizard.'],
    ['./images/other/other_gals.jpg','RENOMA KOSETH and SUVAL NAIA. Two characters from another project related to Abyrinth, they also represent explorations of the visual desing of their respective alien species.'],
    ['./images/other/other_koseth.png','RENOMA KOSETH. An early exploration of the main character of a project aset in the same universe as Abyrinth.'],
    ['./images/other/other_preEideron.jpg','An early exploration for a fantasy character.'],
    ['./images/other/other_scout.png','ZOKOT SCOUT. A creature design for a scout unit of a an army of monsters of the red desert.'],
    ['./images/other/other_skyworld.png','ABOVE. The skyworld from the 2022 game jam game Cloud Raider. I created a set of reusable assets for different islands and swtructures as well as clouds of different shapes. It was meant to have an idyllic feeling when contrasted with the ruined world beneath the clouds.'],
    ['./images/other/other_wind.png','WINDRIDER. A low-poly pixel-textured space ship. It was meant to evoke ships like the X-Wing from Starwars and the Arwing from Starfox while also adding a flare. The ship was made to be very pointy as a contrast to the other ships which tended to be more rounded.'],
    ['./images/other/other_xopexdance.png','DANCING BLADEWIZARD. My goal for this piece was to express the idea that the character was balanced up on the staff.'],
    ['./images/other/other_Zonzovir_3.png','ZONZOVIR. '],
    ['./images/other/other_dunefolk1.png','CHIEFTESS OF THE SOTOTHI. '],
    ['./images/other/other_eideron2.png','EIDERON, BEARER OF THE CRESCENT BLADE. '],
    ['./images/other/other_ghost.png','THE GHOST.'],
    ['./images/other/other_antisquare.jpg','THE ANTISQUARE.']

]

var halenImgs = [
    ['./images/halen/relic_halen_up.png','A piece featuring the final look of Halen as of the latest development work on Relicbound. It was done to show her in motion.'],
    ['./images/halen/relic_halen_sheet.png','A model sheet for Halen as of the latest development of Relicbound.'],
    ['./images/halen/halen_crisp.png','A halen design created after development was put on hold. I was exploring alternative styles and shapes.'],
    ['./images/halen/halen_bright.png','A halen design created after development was put on hold. I was trying different posing as well as changing the designs and adding yellow.'],
    ['./images/halen/halen_purple.png','A halen design created after development was put on hold. Exploring different shapes and colours and a different feeling for the Sharp arm. This was a piece exploring what it might look like if both Halen and Sharp were talking to someone.'],
    ['./images/halen/halen_dynamic.png','A halen design created after development was put on hold. This was an exploration to see what it would look like if Halen\'s colour scheme were simplified.'],
    ['./images/halen/halen_casual.png','A piece exploring what Halen might look like when she is not wearing armour. I wanted to emphasize her scrappiness and personality as well as hint at the injuries she has sustained on her missions.'],
    ['./images/halen/halen_gauntlet.png','A halen design created after development was put on hold. An exploration of taking the Sharp arm and turning it into a gauntlet.'],
    ['./images/halen/halen_grab.png','A halen design created after development was put on hold. A quick exploration of taking something much closer with the original design and adding the new crystalline idea of Sharp.'],
    ['./images/halen/halen_scarves.png','A halen design created after development was put on hold. This was an exploration of bringing the design into a more simplified colour scheme as well exploring a more skeletal idea for the Sharp arm.'],
    ['./images/halen/halen_spear.png','A halen design created after development was put on hold. Inspired by concepts from the initial student project version of the game as well as exploring the idea of Sharp being a spear.'],
    ['./images/halen/halen_space.jpg','A halen design created after development was put on hold. A different take on Halen.'],
    ['./images/halen/halen_first.png','A halen design created after development was put on hold. This piece explored an alternate colour scheme as well as shapes. It imagined that Sharp, instead of being a sword, was a crystal which could potentially be utilized in different ways at the end of Halen\'s Sharp arm.']
]

var relicImgs = [
    ['./images/relic/relic_skirm3.png','THE SKIRMISHER. The Third iteration of the design. It was made to emphasize its mobility and articulated cannons.'],
    ['./images/relic/relic_skirm2.png','The second iteration of the skirmisher design. I emphasized the speed.'],
    ['./images/relic/relic_skirm.png','The first iteration of the skirmisher. I wanted to emphasize speed as well as play with cannons as a second set of arms. Because the enemy would be a threat in melee and at range, I chose purple for it given that we used red for melee enemies and blue for ranged enemies.'],
    ['./images/relic/relic_brawler.png','THE BRAWLER. Meant to be the basic fodder enemy of the game.'],
    ['./images/relic/relic_brawler_sheet.png','The model sheet for the brawler.'],
    ['./images/relic/relic_gunner.png','THE GUNNER. A tougher enemy than the brawler, and mostly ranged. It has a broad silhouette to emphasize toughness.'],
    ['./images/relic/relic_gunner_sheet.png','The model sheet for the gunner.'],
    ['./images/relic/relic_asltgunner.png','THE ASSAULT GUNNER. A heavier boss version of the gunner. Made even bulkier than the gunner.'],
    ['./images/relic/relic_foreman.png','THE BRAWLER FOREMAN. A boss version of the brawler. A wide hat and jackhammer arm were added as well as a hardhat were incorporated.'],
    ['./images/relic/relic_charger.png','THE CHARGER. A boss enemy that relies on pure physicality.'],
    ['./images/relic/relic_docship.png','A voxel mockup of the vessel of the Professor, the villain.'],
    ['./images/relic/relic_float.png','THE FIXER. A floating enemy which repairs and transports other robots.'],
    ['./images/relic/relic_flauripan.png','Pyress Flauripan. An alien archeologist who who haplessly assisted the Professor in locating the planet Teltona.'],
    ['./images/relic/relic_hship2.png','Concept for Halen\'s ship.'],
    ['./images/relic/relic_hship.png','A second version of Halen\'s ship. This time, reimagined as a slightly larger vessel.'],
    ['./images/relic/relic_theravall2.png','A concept for Theravall, the Professor\'s henchman sent to dispatch Halen and take the sword from her.'],
    ['./images/relic/relic_theravall.png','Another concept for Theravall.'],
    ['./images/relic/relic_doctor.png','An initial concept for the Professor. At this time, he was seen as more of an explorer.'],
    ['./images/relic/relic_revenant.png','REVENANT. An enemy found in the temple on Teltona. An ancient guardian created by a solemn oath to stop any who would take the sword.'],
    ['./images/relic/relic_sniper.png','THE SNIPER. A ranged enemy.']
]

var vfxImgs = [abyrinthImgs[2],abyrinthImgs[4],abyrinthImgs[17],evasiveImgs[0],evasiveImgs[2],evasiveImgs[3],evasiveImgs[4],evasiveImgs[5],blobsImgs[0],blobsImgs[1],blobsImgs[2]]
var threedeeImgs = [abyrinthImgs[0],abyrinthImgs[3],abyrinthImgs[5],abyrinthImgs[7],abyrinthImgs[9],abyrinthImgs[11],abyrinthImgs[12],relicImgs[13],mushImgs[11],mushImgs[12],mushImgs[13],mushImgs[14],mushImgs[15],mushImgs[16],evasiveImgs[6],evasiveImgs[7],evasiveImgs[8],otherImgs[2],otherImgs[10],otherImgs[11]]
var programmingImgs = []
var twodeeImgs = [logoImgs[0],logoImgs[1],logoImgs[2],logoImgs[3],logoImgs[4],logoImgs[5],abyrinthImgs[1],abyrinthImgs[6],abyrinthImgs[8],abyrinthImgs[10],halenImgs[0],halenImgs[1],halenImgs[2],halenImgs[3],halenImgs[4],halenImgs[5],halenImgs[6],halenImgs[7],halenImgs[8],halenImgs[9],halenImgs[10],halenImgs[11],halenImgs[12], relicImgs[0], relicImgs[1],relicImgs[2],relicImgs[3],relicImgs[4],relicImgs[5],relicImgs[6],relicImgs[7],relicImgs[8],relicImgs[9],relicImgs[11],relicImgs[12],relicImgs[14],relicImgs[15],relicImgs[16],relicImgs[17],relicImgs[18],relicImgs[19],mushImgs[0],mushImgs[1],mushImgs[2],mushImgs[3],mushImgs[4],mushImgs[5],mushImgs[6],mushImgs[7],mushImgs[8],mushImgs[9],mushImgs[10],blobsImgs[5],otherImgs[0],otherImgs[1],otherImgs[3],otherImgs[4],otherImgs[5],otherImgs[6],otherImgs[7],otherImgs[8],otherImgs[9],otherImgs[12],otherImgs[13]]
var uiImgs = []
